// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVWAc1AEvqAHowEXXxiYbyTanXfAhy6A',
    appId: '1:199451659471:web:0b6f387e2224ee0341fbba',
    messagingSenderId: '199451659471',
    projectId: 'project-ii-603da',
    authDomain: 'project-ii-603da.firebaseapp.com',
    storageBucket: 'project-ii-603da.appspot.com',
    measurementId: 'G-6QG3Y1DEF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeIuygu35xYUQGSphdUb19IHLzRFI7F1c',
    appId: '1:199451659471:android:88037cdc26a40da441fbba',
    messagingSenderId: '199451659471',
    projectId: 'project-ii-603da',
    storageBucket: 'project-ii-603da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE3g4uhrU_XutpChJpyyQIfeFIRgYq37Q',
    appId: '1:199451659471:ios:115c40a1cbc807da41fbba',
    messagingSenderId: '199451659471',
    projectId: 'project-ii-603da',
    storageBucket: 'project-ii-603da.appspot.com',
    iosBundleId: 'com.example.projectIi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE3g4uhrU_XutpChJpyyQIfeFIRgYq37Q',
    appId: '1:199451659471:ios:9b2ff54c49d83a8c41fbba',
    messagingSenderId: '199451659471',
    projectId: 'project-ii-603da',
    storageBucket: 'project-ii-603da.appspot.com',
    iosBundleId: 'com.example.projectIi.RunnerTests',
  );
}
